[package]
name = "test_base"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
simple_logger = "5.0.0"
test-context = "0.3.0"
